ARG ARG_RUBY_VERSION

# ==================== #
#      First Image     #
# ==================== #
FROM ruby:${ARG_RUBY_VERSION} AS intermediate

ARG ARG_BUNDLER_VERSION
ARG ARG_APP_PATH
ARG ARG_RUBYGEMS_VERSION

RUN apt-get update -qq && \
    apt-get install -y build-essential \
    libpq-dev \
    nodejs \
    imagemagick \
    && apt-get clean autoclean \
    && apt-get autoremove -y \
    && rm -rf \
    /var/lib/apt \
    /var/lib/dpkg \
    /var/lib/cache \
    /var/lib/log

ENV BUNDLE_PATH /bundle
ENV GEM_HOME /bundle
ENV BUNDLE_JOBS 20
ENV BUNDLE_RETRY 5
ENV BUNDLE_WITHOUT production development
ENV BUNDLE_CACHE_ALL true
ENV BUNDLER_VERSION ${ARG_BUNDLER_VERSION}
ENV RUBYGEMS_VERSION ${ARG_RUBYGEMS_VERSION}

ENV APP_PATH ${ARG_APP_PATH}

WORKDIR ${ARG_APP_PATH}

COPY Gemfile ${ARG_APP_PATH}
COPY Gemfile.lock ${ARG_APP_PATH}

RUN gem update --system ${RUBYGEMS_VERSION}

RUN gem install bundler:${BUNDLER_VERSION}

RUN bundle install

ENV RAILS_ENV test
ENV RACK_ENV test

# ==================== #
#     Second Image     #
# ==================== #
FROM ruby:${ARG_RUBY_VERSION}

ARG ARG_BUNDLER_VERSION
ARG ARG_APP_PATH
ARG ARG_RUBYGEMS_VERSION

RUN apt-get update -qq && \
    apt-get install -y build-essential \
    libpq-dev \
    nodejs \
    chromium-driver \
    chromium \
    && rm -rf /var/lib/apt/lists/*

ENV BUNDLE_PATH /bundle
ENV GEM_HOME /bundle
ENV BUNDLE_JOBS 20
ENV BUNDLE_RETRY 5
ENV BUNDLE_WITHOUT production development
ENV BUNDLE_CACHE_ALL true
ENV BUNDLER_VERSION ${ARG_BUNDLER_VERSION}
# ENV BUNDLE_BIN ${BUNDLE_PATH}/bin
# ENV BUNDLE_APP_CONFIG ${BUNDLE_PATH}

ENV APP_PATH ${ARG_APP_PATH}

WORKDIR ${ARG_APP_PATH}

COPY --from=intermediate /bundle /bundle

COPY Gemfile ${ARG_APP_PATH}
COPY Gemfile.lock ${ARG_APP_PATH}

RUN bundle install

RUN cp -vf /usr/bin/chromedriver /bundle/ruby/2.7.0/bin

ENV PATH ${ARG_APP_PATH}/bin:${BUNDLE_PATH}/bin:${PATH}

ENV RAILS_ENV test
ENV RACK_ENV test